[project]
name = "task-progress-estimator"
version = "0.1.0"
description = "Agile task progress estimator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "streamlit>=1.52.1",
    "streamlit-local-storage>=0.0.25",
]
